name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout del código fuente
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Configurar Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # 3. Instalar dependencias (si tienes package.json en la raíz)
      - name: Install dependencies
        run: |
          if [ -f package.json ]; then
            npm install
          fi

      # 4. Minificar JavaScript en la raíz
      - name: Minify JavaScript
        run: |
          npm install -g terser
          terser *.js --compress --mangle --output dist/

      # 5. Publicar en GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
